package com.scommix.WebServices.Common;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/1/2014 2:30:02 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.io.Serializable;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class online implements Serializable {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */

	/**
	 * 
	 */

	public String institutename;
    public String totalamount;
    public String previousbalance;
    public String totalconcession;
    public String feehead;
    public String feesfrequency;
    public String amount;
    public String instituteid;
    public String friendcount;
    public String fathername;
    public String mothername;
    public String mobileno;
    public String landlineno;
    public String siblings;
    public String numberofsiblings;
    public String _classField;
    public String fatheroccupation;
    public String motheroccupation;
    public String userfriendid;
    public String nid;
    public String postedtime;
    public String text;
    public String ntype;
    public String hyperlink;
    public String active;
    public String description;
    public String staticpagename;
    public String staticpageid;
    public String statusid;
    public String userstatusid;
    public String statustime;
    public String commentid;
    public String comment;
    public String commenttime;
    public String userpic;
    public String count;
    public String countryname;
    public String message;
    public String messageid;
    public String senderid;
    public String friendid;
    public String senttime;
    public String firstname;
    public String lastname;
    public String gender;
    public String dob;
    public String addressline1;
    public String addressline2;
    public String countryid;
    public String zipcode;
    public String state;
    public String email;
    public String city;
    public String name;
    public String username;
    public String isonline;
    public String userid;
    public String receiverid;
    public String c_addressline1;
    public String c_addressline2;
    public String workdetail;
    public String date;
    public String svimclassidField;
    public String classIdField;
    public String subject;
    public String examinationtypes;
    public String academicyear;
    public String finalgrade;
    public String finalpercentage;
    public String marks;
    public String obtainedmarks;
    public String totalmarks;
    public String subjectMarks;
    public String timings;
    public String userprofileimage;
    public String liketag;
    
    public String getLiketag() {
		return liketag;
	}







	public void setLiketag(String liketag) {
		this.liketag = liketag;
	}







	public online(){}
    
    
    
 



	public online(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("institutename"))
        {
            Object obj = soapObject.getProperty("institutename");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                institutename = j.toString();
            }else if (obj!= null && obj instanceof String){
                institutename = (String) obj;
            }
        }
        if (soapObject.hasProperty("totalamount"))
        {
            Object obj = soapObject.getProperty("totalamount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                totalamount = j.toString();
            }else if (obj!= null && obj instanceof String){
                totalamount = (String) obj;
            }
        }
        if (soapObject.hasProperty("previousbalance"))
        {
            Object obj = soapObject.getProperty("previousbalance");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                previousbalance = j.toString();
            }else if (obj!= null && obj instanceof String){
                previousbalance = (String) obj;
            }
        }
        if (soapObject.hasProperty("totalconcession"))
        {
            Object obj = soapObject.getProperty("totalconcession");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                totalconcession = j.toString();
            }else if (obj!= null && obj instanceof String){
                totalconcession = (String) obj;
            }
        }
        if (soapObject.hasProperty("feehead"))
        {
            Object obj = soapObject.getProperty("feehead");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                feehead = j.toString();
            }else if (obj!= null && obj instanceof String){
                feehead = (String) obj;
            }
        }
        if (soapObject.hasProperty("feesfrequency"))
        {
            Object obj = soapObject.getProperty("feesfrequency");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                feesfrequency = j.toString();
            }else if (obj!= null && obj instanceof String){
                feesfrequency = (String) obj;
            }
        }
        if (soapObject.hasProperty("amount"))
        {
            Object obj = soapObject.getProperty("amount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                amount = j.toString();
            }else if (obj!= null && obj instanceof String){
                amount = (String) obj;
            }
        }
        if (soapObject.hasProperty("instituteid"))
        {
            Object obj = soapObject.getProperty("instituteid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                instituteid = j.toString();
            }else if (obj!= null && obj instanceof String){
                instituteid = (String) obj;
            }
        }
        if (soapObject.hasProperty("friendcount"))
        {
            Object obj = soapObject.getProperty("friendcount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                friendcount = j.toString();
            }else if (obj!= null && obj instanceof String){
                friendcount = (String) obj;
            }
        }
        if (soapObject.hasProperty("fathername"))
        {
            Object obj = soapObject.getProperty("fathername");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fathername = j.toString();
            }else if (obj!= null && obj instanceof String){
                fathername = (String) obj;
            }
        }
        if (soapObject.hasProperty("mothername"))
        {
            Object obj = soapObject.getProperty("mothername");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mothername = j.toString();
            }else if (obj!= null && obj instanceof String){
                mothername = (String) obj;
            }
        }
        if (soapObject.hasProperty("mobileno"))
        {
            Object obj = soapObject.getProperty("mobileno");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mobileno = j.toString();
            }else if (obj!= null && obj instanceof String){
                mobileno = (String) obj;
            }
        }
        if (soapObject.hasProperty("landlineno"))
        {
            Object obj = soapObject.getProperty("landlineno");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                landlineno = j.toString();
            }else if (obj!= null && obj instanceof String){
                landlineno = (String) obj;
            }
        }
        if (soapObject.hasProperty("siblings"))
        {
            Object obj = soapObject.getProperty("siblings");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                siblings = j.toString();
            }else if (obj!= null && obj instanceof String){
                siblings = (String) obj;
            }
        }
        if (soapObject.hasProperty("numberofsiblings"))
        {
            Object obj = soapObject.getProperty("numberofsiblings");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                numberofsiblings = j.toString();
            }else if (obj!= null && obj instanceof String){
                numberofsiblings = (String) obj;
            }
        }
        if (soapObject.hasProperty("_class"))
        {
            Object obj = soapObject.getProperty("_class");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                _classField = j.toString();
            }else if (obj!= null && obj instanceof String){
                _classField = (String) obj;
            }
        }
        if (soapObject.hasProperty("fatheroccupation"))
        {
            Object obj = soapObject.getProperty("fatheroccupation");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fatheroccupation = j.toString();
            }else if (obj!= null && obj instanceof String){
                fatheroccupation = (String) obj;
            }
        }
        if (soapObject.hasProperty("motheroccupation"))
        {
            Object obj = soapObject.getProperty("motheroccupation");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                motheroccupation = j.toString();
            }else if (obj!= null && obj instanceof String){
                motheroccupation = (String) obj;
            }
        }
        if (soapObject.hasProperty("userfriendid"))
        {
            Object obj = soapObject.getProperty("userfriendid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                userfriendid = j.toString();
            }else if (obj!= null && obj instanceof String){
                userfriendid = (String) obj;
            }
        }
        if (soapObject.hasProperty("nid"))
        {
            Object obj = soapObject.getProperty("nid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                nid = j.toString();
            }else if (obj!= null && obj instanceof String){
                nid = (String) obj;
            }
        }
        if (soapObject.hasProperty("postedtime"))
        {
            Object obj = soapObject.getProperty("postedtime");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                postedtime = j.toString();
            }else if (obj!= null && obj instanceof String){
                postedtime = (String) obj;
            }
        }
        if (soapObject.hasProperty("text"))
        {
            Object obj = soapObject.getProperty("text");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                text = j.toString();
            }else if (obj!= null && obj instanceof String){
                text = (String) obj;
            }
        }
        if (soapObject.hasProperty("ntype"))
        {
            Object obj = soapObject.getProperty("ntype");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                ntype = j.toString();
            }else if (obj!= null && obj instanceof String){
                ntype = (String) obj;
            }
        }
        if (soapObject.hasProperty("hyperlink"))
        {
            Object obj = soapObject.getProperty("hyperlink");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                hyperlink = j.toString();
            }else if (obj!= null && obj instanceof String){
                hyperlink = (String) obj;
            }
        }
        if (soapObject.hasProperty("active"))
        {
            Object obj = soapObject.getProperty("active");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                active = j.toString();
            }else if (obj!= null && obj instanceof String){
                active = (String) obj;
            }
        }
        if (soapObject.hasProperty("description"))
        {
            Object obj = soapObject.getProperty("description");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                description = j.toString();
            }else if (obj!= null && obj instanceof String){
                description = (String) obj;
            }
        }
        if (soapObject.hasProperty("staticpagename"))
        {
            Object obj = soapObject.getProperty("staticpagename");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                staticpagename = j.toString();
            }else if (obj!= null && obj instanceof String){
                staticpagename = (String) obj;
            }
        }
        if (soapObject.hasProperty("staticpageid"))
        {
            Object obj = soapObject.getProperty("staticpageid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                staticpageid = j.toString();
            }else if (obj!= null && obj instanceof String){
                staticpageid = (String) obj;
            }
        }
        if (soapObject.hasProperty("statusid"))
        {
            Object obj = soapObject.getProperty("statusid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                statusid = j.toString();
            }else if (obj!= null && obj instanceof String){
                statusid = (String) obj;
            }
        }
        if (soapObject.hasProperty("userstatusid"))
        {
            Object obj = soapObject.getProperty("userstatusid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                userstatusid = j.toString();
            }else if (obj!= null && obj instanceof String){
                userstatusid = (String) obj;
            }
        }
        if (soapObject.hasProperty("statustime"))
        {
            Object obj = soapObject.getProperty("statustime");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                statustime = j.toString();
            }else if (obj!= null && obj instanceof String){
                statustime = (String) obj;
            }
        }
        if (soapObject.hasProperty("commentid"))
        {
            Object obj = soapObject.getProperty("commentid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                commentid = j.toString();
            }else if (obj!= null && obj instanceof String){
                commentid = (String) obj;
            }
        }
        if (soapObject.hasProperty("comment"))
        {
            Object obj = soapObject.getProperty("comment");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                comment = j.toString();
            }else if (obj!= null && obj instanceof String){
                comment = (String) obj;
            }
        }
        if (soapObject.hasProperty("commenttime"))
        {
            Object obj = soapObject.getProperty("commenttime");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                commenttime = j.toString();
            }else if (obj!= null && obj instanceof String){
                commenttime = (String) obj;
            }
        }
        if (soapObject.hasProperty("userpic"))
        {
            Object obj = soapObject.getProperty("userpic");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                userpic = j.toString();
            }else if (obj!= null && obj instanceof String){
                userpic = (String) obj;
            }
        }
        if (soapObject.hasProperty("count"))
        {
            Object obj = soapObject.getProperty("count");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                count = j.toString();
            }else if (obj!= null && obj instanceof String){
                count = (String) obj;
            }
        }
        if (soapObject.hasProperty("countryname"))
        {
            Object obj = soapObject.getProperty("countryname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                countryname = j.toString();
            }else if (obj!= null && obj instanceof String){
                countryname = (String) obj;
            }
        }
        if (soapObject.hasProperty("message"))
        {
            Object obj = soapObject.getProperty("message");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                message = j.toString();
            }else if (obj!= null && obj instanceof String){
                message = (String) obj;
            }
        }
        if (soapObject.hasProperty("messageid"))
        {
            Object obj = soapObject.getProperty("messageid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                messageid = j.toString();
            }else if (obj!= null && obj instanceof String){
                messageid = (String) obj;
            }
        }
        if (soapObject.hasProperty("senderid"))
        {
            Object obj = soapObject.getProperty("senderid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                senderid = j.toString();
            }else if (obj!= null && obj instanceof String){
                senderid = (String) obj;
            }
        }
        if (soapObject.hasProperty("friendid"))
        {
            Object obj = soapObject.getProperty("friendid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                friendid = j.toString();
            }else if (obj!= null && obj instanceof String){
                friendid = (String) obj;
            }
        }
        if (soapObject.hasProperty("senttime"))
        {
            Object obj = soapObject.getProperty("senttime");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                senttime = j.toString();
            }else if (obj!= null && obj instanceof String){
                senttime = (String) obj;
            }
        }
        if (soapObject.hasProperty("firstname"))
        {
            Object obj = soapObject.getProperty("firstname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                firstname = j.toString();
            }else if (obj!= null && obj instanceof String){
                firstname = (String) obj;
            }
        }
        if (soapObject.hasProperty("lastname"))
        {
            Object obj = soapObject.getProperty("lastname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lastname = j.toString();
            }else if (obj!= null && obj instanceof String){
                lastname = (String) obj;
            }
        }
        if (soapObject.hasProperty("gender"))
        {
            Object obj = soapObject.getProperty("gender");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                gender = j.toString();
            }else if (obj!= null && obj instanceof String){
                gender = (String) obj;
            }
        }
        if (soapObject.hasProperty("dob"))
        {
            Object obj = soapObject.getProperty("dob");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                dob = j.toString();
            }else if (obj!= null && obj instanceof String){
                dob = (String) obj;
            }
        }
        if (soapObject.hasProperty("addressline1"))
        {
            Object obj = soapObject.getProperty("addressline1");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                addressline1 = j.toString();
            }else if (obj!= null && obj instanceof String){
                addressline1 = (String) obj;
            }
        }
        if (soapObject.hasProperty("addressline2"))
        {
            Object obj = soapObject.getProperty("addressline2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                addressline2 = j.toString();
            }else if (obj!= null && obj instanceof String){
                addressline2 = (String) obj;
            }
        }
        if (soapObject.hasProperty("countryid"))
        {
            Object obj = soapObject.getProperty("countryid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                countryid = j.toString();
            }else if (obj!= null && obj instanceof String){
                countryid = (String) obj;
            }
        }
        if (soapObject.hasProperty("zipcode"))
        {
            Object obj = soapObject.getProperty("zipcode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                zipcode = j.toString();
            }else if (obj!= null && obj instanceof String){
                zipcode = (String) obj;
            }
        }
        if (soapObject.hasProperty("state"))
        {
            Object obj = soapObject.getProperty("state");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                state = j.toString();
            }else if (obj!= null && obj instanceof String){
                state = (String) obj;
            }
        }
        if (soapObject.hasProperty("email"))
        {
            Object obj = soapObject.getProperty("email");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                email = j.toString();
            }else if (obj!= null && obj instanceof String){
                email = (String) obj;
            }
        }
        if (soapObject.hasProperty("city"))
        {
            Object obj = soapObject.getProperty("city");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                city = j.toString();
            }else if (obj!= null && obj instanceof String){
                city = (String) obj;
            }
        }
        if (soapObject.hasProperty("name"))
        {
            Object obj = soapObject.getProperty("name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                name = j.toString();
            }else if (obj!= null && obj instanceof String){
                name = (String) obj;
            }
        }
        if (soapObject.hasProperty("username"))
        {
            Object obj = soapObject.getProperty("username");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                username = j.toString();
            }else if (obj!= null && obj instanceof String){
                username = (String) obj;
            }
        }
        if (soapObject.hasProperty("isonline"))
        {
            Object obj = soapObject.getProperty("isonline");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                isonline = j.toString();
            }else if (obj!= null && obj instanceof String){
                isonline = (String) obj;
            }
        }
        if (soapObject.hasProperty("userid"))
        {
            Object obj = soapObject.getProperty("userid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                userid = j.toString();
            }else if (obj!= null && obj instanceof String){
                userid = (String) obj;
            }
        }
        if (soapObject.hasProperty("receiverid"))
        {
            Object obj = soapObject.getProperty("receiverid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                receiverid = j.toString();
            }else if (obj!= null && obj instanceof String){
                receiverid = (String) obj;
            }
        }
        if (soapObject.hasProperty("c_addressline1"))
        {
            Object obj = soapObject.getProperty("c_addressline1");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                c_addressline1 = j.toString();
            }else if (obj!= null && obj instanceof String){
                c_addressline1 = (String) obj;
            }
        }
        if (soapObject.hasProperty("c_addressline2"))
        {
            Object obj = soapObject.getProperty("c_addressline2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                c_addressline2 = j.toString();
            }else if (obj!= null && obj instanceof String){
                c_addressline2 = (String) obj;
            }
        }
        if (soapObject.hasProperty("workdetail"))
        {
            Object obj = soapObject.getProperty("workdetail");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                workdetail = j.toString();
            }else if (obj!= null && obj instanceof String){
                workdetail = (String) obj;
            }
        }
        if (soapObject.hasProperty("date"))
        {
            Object obj = soapObject.getProperty("date");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                date = j.toString();
            }else if (obj!= null && obj instanceof String){
                date = (String) obj;
            }
        }
        if (soapObject.hasProperty("svimeduid"))
        {
            Object obj = soapObject.getProperty("svimeduid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                svimclassidField = j.toString();
            }
            
            else if (obj!= null && obj instanceof String){
                svimclassidField = (String) obj;
            }
        }
        if (soapObject.hasProperty("classId"))
        {
            Object obj = soapObject.getProperty("classId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                classIdField = j.toString();
            }else if (obj!= null && obj instanceof String){
                classIdField = (String) obj;
            }
        }
        if (soapObject.hasProperty("subject"))
        {
            Object obj = soapObject.getProperty("subject");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                subject = j.toString();
            }else if (obj!= null && obj instanceof String){
                subject = (String) obj;
            }
        }
        if (soapObject.hasProperty("examinationtypes"))
        {
            Object obj = soapObject.getProperty("examinationtypes");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                examinationtypes = j.toString();
            }else if (obj!= null && obj instanceof String){
                examinationtypes = (String) obj;
            }
        }
        if (soapObject.hasProperty("academicyear"))
        {
            Object obj = soapObject.getProperty("academicyear");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                academicyear = j.toString();
            }else if (obj!= null && obj instanceof String){
                academicyear = (String) obj;
            }
        }
        if (soapObject.hasProperty("finalgrade"))
        {
            Object obj = soapObject.getProperty("finalgrade");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                finalgrade = j.toString();
            }else if (obj!= null && obj instanceof String){
                finalgrade = (String) obj;
            }
        }
        if (soapObject.hasProperty("finalpercentage"))
        {
            Object obj = soapObject.getProperty("finalpercentage");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                finalpercentage = j.toString();
            }else if (obj!= null && obj instanceof String){
                finalpercentage = (String) obj;
            }
        }
        if (soapObject.hasProperty("marks"))
        {
            Object obj = soapObject.getProperty("marks");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                marks = j.toString();
            }else if (obj!= null && obj instanceof String){
                marks = (String) obj;
            }
        }
        if (soapObject.hasProperty("obtainedmarks"))
        {
            Object obj = soapObject.getProperty("obtainedmarks");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                obtainedmarks = j.toString();
            }else if (obj!= null && obj instanceof String){
                obtainedmarks = (String) obj;
            }
        }
        if (soapObject.hasProperty("totalmarks"))
        {
            Object obj = soapObject.getProperty("totalmarks");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                totalmarks = j.toString();
            }else if (obj!= null && obj instanceof String){
                totalmarks = (String) obj;
            }
        }
        if (soapObject.hasProperty("userprofileimage"))
        {
            Object obj = soapObject.getProperty("userprofileimage");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                userprofileimage = j.toString();
            }else if (obj!= null && obj instanceof String){
                userprofileimage = (String) obj;
            }
        }
      
        if (soapObject.hasProperty("subjectMarks"))
        {
            Object obj = soapObject.getProperty("subjectMarks");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                subjectMarks = j.toString();
            }else if (obj!= null && obj instanceof String){
                subjectMarks = (String) obj;
            }
        }
        if (soapObject.hasProperty("Timings"))
        {
            Object obj = soapObject.getProperty("Timings");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                timings = j.toString();
            }else if (obj!= null && obj instanceof String){
                timings = (String) obj;
            }
        }
        
        
        
        
    }
//    @Override
//    public Object getProperty(int arg0) {
//        switch(arg0){
//            case 0:
//                return institutename;
//            case 1:
//                return totalamount;
//            case 2:
//                return previousbalance;
//            case 3:
//                return totalconcession;
//            case 4:
//                return feehead;
//            case 5:
//                return feesfrequency;
//            case 6:
//                return amount;
//            case 7:
//                return instituteid;
//            case 8:
//                return friendcount;
//            case 9:
//                return fathername;
//            case 10:
//                return mothername;
//            case 11:
//                return mobileno;
//            case 12:
//                return landlineno;
//            case 13:
//                return siblings;
//            case 14:
//                return numberofsiblings;
//            case 15:
//                return _classField;
//            case 16:
//                return fatheroccupation;
//            case 17:
//                return motheroccupation;
//            case 18:
//                return userfriendid;
//            case 19:
//                return nid;
//            case 20:
//                return postedtime;
//            case 21:
//                return text;
//            case 22:
//                return ntype;
//            case 23:
//                return hyperlink;
//            case 24:
//                return active;
//            case 25:
//                return description;
//            case 26:
//                return staticpagename;
//            case 27:
//                return staticpageid;
//            case 28:
//                return statusid;
//            case 29:
//                return userstatusid;
//            case 30:
//                return statustime;
//            case 31:
//                return commentid;
//            case 32:
//                return comment;
//            case 33:
//                return commenttime;
//            case 34:
//                return userpic;
//            case 35:
//                return count;
//            case 36:
//                return countryname;
//            case 37:
//                return message;
//            case 38:
//                return messageid;
//            case 39:
//                return senderid;
//            case 40:
//                return friendid;
//            case 41:
//                return senttime;
//            case 42:
//                return firstname;
//            case 43:
//                return lastname;
//            case 44:
//                return gender;
//            case 45:
//                return dob;
//            case 46:
//                return addressline1;
//            case 47:
//                return addressline2;
//            case 48:
//                return countryid;
//            case 49:
//                return zipcode;
//            case 50:
//                return state;
//            case 51:
//                return email;
//            case 52:
//                return city;
//            case 53:
//                return name;
//            case 54:
//                return username;
//            case 55:
//                return isonline;
//            case 56:
//                return userid;
//            case 57:
//                return receiverid;
//            case 58:
//                return c_addressline1;
//            case 59:
//                return c_addressline2;
//            case 60:
//                return workdetail;
//            case 61:
//                return date;
//            case 62:
//                return svimclassidField;
//            case 63:
//                return classIdField;
//            case 64:
//                return subject;
//            case 65:
//                return examinationtypes;
//            case 66:
//                return academicyear;
//            case 67:
//                return finalgrade;
//            case 68:
//                return finalpercentage;
//            case 69:
//                return marks;
//            case 70:
//                return obtainedmarks;
//            case 71:
//                return totalmarks;
//            case 72:
//                return subjectMarks;
//            case 73:
//                return timings;
//        }
//        return null;
//    }
//    
//    @Override
//    public int getPropertyCount() {
//        return 74;
//    }
//    
//    @Override
//    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
//        switch(index){
//            case 0:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "institutename";
//                break;
//            case 1:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "totalamount";
//                break;
//            case 2:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "previousbalance";
//                break;
//            case 3:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "totalconcession";
//                break;
//            case 4:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "feehead";
//                break;
//            case 5:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "feesfrequency";
//                break;
//            case 6:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "amount";
//                break;
//            case 7:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "instituteid";
//                break;
//            case 8:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "friendcount";
//                break;
//            case 9:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "fathername";
//                break;
//            case 10:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "mothername";
//                break;
//            case 11:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "mobileno";
//                break;
//            case 12:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "landlineno";
//                break;
//            case 13:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "siblings";
//                break;
//            case 14:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "numberofsiblings";
//                break;
//            case 15:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "_class";
//                break;
//            case 16:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "fatheroccupation";
//                break;
//            case 17:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "motheroccupation";
//                break;
//            case 18:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "userfriendid";
//                break;
//            case 19:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "nid";
//                break;
//            case 20:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "postedtime";
//                break;
//            case 21:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "text";
//                break;
//            case 22:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "ntype";
//                break;
//            case 23:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "hyperlink";
//                break;
//            case 24:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "active";
//                break;
//            case 25:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "description";
//                break;
//            case 26:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "staticpagename";
//                break;
//            case 27:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "staticpageid";
//                break;
//            case 28:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "statusid";
//                break;
//            case 29:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "userstatusid";
//                break;
//            case 30:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "statustime";
//                break;
//            case 31:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "commentid";
//                break;
//            case 32:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "comment";
//                break;
//            case 33:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "commenttime";
//                break;
//            case 34:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "userpic";
//                break;
//            case 35:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "count";
//                break;
//            case 36:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "countryname";
//                break;
//            case 37:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "message";
//                break;
//            case 38:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "messageid";
//                break;
//            case 39:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "senderid";
//                break;
//            case 40:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "friendid";
//                break;
//            case 41:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "senttime";
//                break;
//            case 42:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "firstname";
//                break;
//            case 43:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "lastname";
//                break;
//            case 44:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "gender";
//                break;
//            case 45:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "dob";
//                break;
//            case 46:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "addressline1";
//                break;
//            case 47:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "addressline2";
//                break;
//            case 48:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "countryid";
//                break;
//            case 49:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "zipcode";
//                break;
//            case 50:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "state";
//                break;
//            case 51:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "email";
//                break;
//            case 52:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "city";
//                break;
//            case 53:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "name";
//                break;
//            case 54:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "username";
//                break;
//            case 55:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "isonline";
//                break;
//            case 56:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "userid";
//                break;
//            case 57:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "receiverid";
//                break;
//            case 58:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "c_addressline1";
//                break;
//            case 59:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "c_addressline2";
//                break;
//            case 60:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "workdetail";
//                break;
//            case 61:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "date";
//                break;
//            case 62:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "svimclassid";
//                break;
//            case 63:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "classId";
//                break;
//            case 64:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "subject";
//                break;
//            case 65:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "examinationtypes";
//                break;
//            case 66:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "academicyear";
//                break;
//            case 67:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "finalgrade";
//                break;
//            case 68:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "finalpercentage";
//                break;
//            case 69:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "marks";
//                break;
//            case 70:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "obtainedmarks";
//                break;
//            case 71:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "totalmarks";
//                break;
//            case 72:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "subjectMarks";
//                break;
//            case 73:
//                info.type = PropertyInfo.STRING_CLASS;
//                info.name = "Timings";
//                break;
//        }
//    }
//    
//    @Override
//    public void setProperty(int arg0, Object arg1) {
//    }



	public String getInstitutename() {
		return institutename;
	}



	public void setInstitutename(String institutename) {
		this.institutename = institutename;
	}



	public String getTotalamount() {
		return totalamount;
	}



	public void setTotalamount(String totalamount) {
		this.totalamount = totalamount;
	}



	public String getPreviousbalance() {
		return previousbalance;
	}



	public void setPreviousbalance(String previousbalance) {
		this.previousbalance = previousbalance;
	}



	public String getTotalconcession() {
		return totalconcession;
	}



	public void setTotalconcession(String totalconcession) {
		this.totalconcession = totalconcession;
	}



	public String getFeehead() {
		return feehead;
	}



	public void setFeehead(String feehead) {
		this.feehead = feehead;
	}



	public String getFeesfrequency() {
		return feesfrequency;
	}



	public void setFeesfrequency(String feesfrequency) {
		this.feesfrequency = feesfrequency;
	}



	public String getAmount() {
		return amount;
	}



	public void setAmount(String amount) {
		this.amount = amount;
	}



	public String getInstituteid() {
		return instituteid;
	}



	public void setInstituteid(String instituteid) {
		this.instituteid = instituteid;
	}



	public String getFriendcount() {
		return friendcount;
	}



	public void setFriendcount(String friendcount) {
		this.friendcount = friendcount;
	}



	public String getFathername() {
		return fathername;
	}



	public void setFathername(String fathername) {
		this.fathername = fathername;
	}



	public String getMothername() {
		return mothername;
	}



	public void setMothername(String mothername) {
		this.mothername = mothername;
	}



	public String getMobileno() {
		return mobileno;
	}



	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}



	public String getLandlineno() {
		return landlineno;
	}



	public void setLandlineno(String landlineno) {
		this.landlineno = landlineno;
	}



	public String getSiblings() {
		return siblings;
	}



	public void setSiblings(String siblings) {
		this.siblings = siblings;
	}



	public String getNumberofsiblings() {
		return numberofsiblings;
	}



	public void setNumberofsiblings(String numberofsiblings) {
		this.numberofsiblings = numberofsiblings;
	}



	public String get_classField() {
		return _classField;
	}



	public void set_classField(String _classField) {
		this._classField = _classField;
	}



	public String getFatheroccupation() {
		return fatheroccupation;
	}



	public void setFatheroccupation(String fatheroccupation) {
		this.fatheroccupation = fatheroccupation;
	}



	public String getMotheroccupation() {
		return motheroccupation;
	}



	public void setMotheroccupation(String motheroccupation) {
		this.motheroccupation = motheroccupation;
	}



	public String getUserfriendid() {
		return userfriendid;
	}



	public void setUserfriendid(String userfriendid) {
		this.userfriendid = userfriendid;
	}



	public String getNid() {
		return nid;
	}



	public void setNid(String nid) {
		this.nid = nid;
	}



	public String getPostedtime() {
		return postedtime;
	}



	public void setPostedtime(String postedtime) {
		this.postedtime = postedtime;
	}



	public String getText() {
		return text;
	}



	public void setText(String text) {
		this.text = text;
	}



	public String getNtype() {
		return ntype;
	}



	public void setNtype(String ntype) {
		this.ntype = ntype;
	}



	public String getHyperlink() {
		return hyperlink;
	}



	public void setHyperlink(String hyperlink) {
		this.hyperlink = hyperlink;
	}



	public String getActive() {
		return active;
	}



	public void setActive(String active) {
		this.active = active;
	}



	public String getDescription() {
		return description;
	}



	public void setDescription(String description) {
		this.description = description;
	}



	public String getStaticpagename() {
		return staticpagename;
	}



	public void setStaticpagename(String staticpagename) {
		this.staticpagename = staticpagename;
	}



	public String getStaticpageid() {
		return staticpageid;
	}



	public void setStaticpageid(String staticpageid) {
		this.staticpageid = staticpageid;
	}



	public String getStatusid() {
		return statusid;
	}



	public void setStatusid(String statusid) {
		this.statusid = statusid;
	}



	public String getUserstatusid() {
		return userstatusid;
	}



	public void setUserstatusid(String userstatusid) {
		this.userstatusid = userstatusid;
	}



	public String getStatustime() {
		return statustime;
	}



	public void setStatustime(String statustime) {
		this.statustime = statustime;
	}



	public String getCommentid() {
		return commentid;
	}



	public void setCommentid(String commentid) {
		this.commentid = commentid;
	}



	public String getComment() {
		return comment;
	}



	public void setComment(String comment) {
		this.comment = comment;
	}



	public String getCommenttime() {
		return commenttime;
	}



	public void setCommenttime(String commenttime) {
		this.commenttime = commenttime;
	}



	public String getUserpic() {
		return userpic;
	}



	public void setUserpic(String userpic) {
		this.userpic = userpic;
	}



	public String getCount() {
		return count;
	}



	public void setCount(String count) {
		this.count = count;
	}



	public String getCountryname() {
		return countryname;
	}



	public void setCountryname(String countryname) {
		this.countryname = countryname;
	}



	public String getMessage() {
		return message;
	}



	public void setMessage(String message) {
		this.message = message;
	}



	public String getMessageid() {
		return messageid;
	}



	public void setMessageid(String messageid) {
		this.messageid = messageid;
	}



	public String getSenderid() {
		return senderid;
	}



	public void setSenderid(String senderid) {
		this.senderid = senderid;
	}



	public String getFriendid() {
		return friendid;
	}



	public void setFriendid(String friendid) {
		this.friendid = friendid;
	}



	public String getSenttime() {
		return senttime;
	}



	public void setSenttime(String senttime) {
		this.senttime = senttime;
	}



	public String getFirstname() {
		return firstname;
	}



	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}



	public String getLastname() {
		return lastname;
	}



	public void setLastname(String lastname) {
		this.lastname = lastname;
	}



	public String getGender() {
		return gender;
	}



	public void setGender(String gender) {
		this.gender = gender;
	}



	public String getDob() {
		return dob;
	}



	public void setDob(String dob) {
		this.dob = dob;
	}



	public String getAddressline1() {
		return addressline1;
	}



	public void setAddressline1(String addressline1) {
		this.addressline1 = addressline1;
	}



	public String getAddressline2() {
		return addressline2;
	}



	public void setAddressline2(String addressline2) {
		this.addressline2 = addressline2;
	}



	public String getCountryid() {
		return countryid;
	}



	public void setCountryid(String countryid) {
		this.countryid = countryid;
	}



	public String getZipcode() {
		return zipcode;
	}



	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}



	public String getState() {
		return state;
	}



	public void setState(String state) {
		this.state = state;
	}



	public String getEmail() {
		return email;
	}



	public void setEmail(String email) {
		this.email = email;
	}



	public String getCity() {
		return city;
	}



	public void setCity(String city) {
		this.city = city;
	}



	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}



	public String getUsername() {
		return username;
	}



	public void setUsername(String username) {
		this.username = username;
	}



	public String getIsonline() {
		return isonline;
	}



	public void setIsonline(String isonline) {
		this.isonline = isonline;
	}



	public String getUserid() {
		return userid;
	}



	public void setUserid(String userid) {
		this.userid = userid;
	}



	public String getReceiverid() {
		return receiverid;
	}



	public void setReceiverid(String receiverid) {
		this.receiverid = receiverid;
	}



	public String getC_addressline1() {
		return c_addressline1;
	}



	public void setC_addressline1(String c_addressline1) {
		this.c_addressline1 = c_addressline1;
	}



	public String getC_addressline2() {
		return c_addressline2;
	}



	public void setC_addressline2(String c_addressline2) {
		this.c_addressline2 = c_addressline2;
	}



	public String getWorkdetail() {
		return workdetail;
	}



	public void setWorkdetail(String workdetail) {
		this.workdetail = workdetail;
	}



	public String getDate() {
		return date;
	}



	public void setDate(String date) {
		this.date = date;
	}



	public String getSvimclassidField() {
		return svimclassidField;
	}



	public void setSvimclassidField(String svimclassidField) {
		this.svimclassidField = svimclassidField;
	}



	public String getClassIdField() {
		return classIdField;
	}



	public void setClassIdField(String classIdField) {
		this.classIdField = classIdField;
	}



	public String getSubject() {
		return subject;
	}



	public void setSubject(String subject) {
		this.subject = subject;
	}



	public String getExaminationtypes() {
		return examinationtypes;
	}



	public void setExaminationtypes(String examinationtypes) {
		this.examinationtypes = examinationtypes;
	}



	public String getAcademicyear() {
		return academicyear;
	}



	public void setAcademicyear(String academicyear) {
		this.academicyear = academicyear;
	}



	public String getFinalgrade() {
		return finalgrade;
	}



	public void setFinalgrade(String finalgrade) {
		this.finalgrade = finalgrade;
	}



	public String getFinalpercentage() {
		return finalpercentage;
	}



	public void setFinalpercentage(String finalpercentage) {
		this.finalpercentage = finalpercentage;
	}



	public String getMarks() {
		return marks;
	}



	public void setMarks(String marks) {
		this.marks = marks;
	}



	public String getObtainedmarks() {
		return obtainedmarks;
	}



	public void setObtainedmarks(String obtainedmarks) {
		this.obtainedmarks = obtainedmarks;
	}



	public String getTotalmarks() {
		return totalmarks;
	}



	public void setTotalmarks(String totalmarks) {
		this.totalmarks = totalmarks;
	}



	public String getSubjectMarks() {
		return subjectMarks;
	}



	public void setSubjectMarks(String subjectMarks) {
		this.subjectMarks = subjectMarks;
	}



	public String getTimings() {
		return timings;
	}



	public void setTimings(String timings) {
		this.timings = timings;
	}



	public String getUserprofileimage() {
		return userprofileimage;
	}



	public void setUserprofileimage(String userprofileimage) {
		this.userprofileimage = userprofileimage;
	}
    
}
