package com.scommix.WebServices.Common;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 8/5/2014 12:36:58 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class StuNotice implements KvmSerializable {
    
    public String noticeid;
    public String name;
    public String _classField;
    public String notice;
    public String send_to__c;
    public String signature__c;
    public String subject__c;
    public String posteddate;
    public String noticecount;
    
    
    
    
    public String getNoticeid() {
		return noticeid;
	}

	public void setNoticeid(String noticeid) {
		this.noticeid = noticeid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String get_classField() {
		return _classField;
	}

	public void set_classField(String _classField) {
		this._classField = _classField;
	}

	public String getNotice() {
		return notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	public String getSend_to__c() {
		return send_to__c;
	}

	public void setSend_to__c(String send_to__c) {
		this.send_to__c = send_to__c;
	}

	public String getSignature__c() {
		return signature__c;
	}

	public void setSignature__c(String signature__c) {
		this.signature__c = signature__c;
	}

	public String getSubject__c() {
		return subject__c;
	}

	public void setSubject__c(String subject__c) {
		this.subject__c = subject__c;
	}

	public String getPosteddate() {
		return posteddate;
	}

	public void setPosteddate(String posteddate) {
		this.posteddate = posteddate;
	}

	public String getNoticecount() {
		return noticecount;
	}

	public void setNoticecount(String noticecount) {
		this.noticecount = noticecount;
	}

	public StuNotice(){}
    
    public StuNotice(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("noticeid"))
        {
            Object obj = soapObject.getProperty("noticeid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                noticeid = j.toString();
            }else if (obj!= null && obj instanceof String){
                noticeid = (String) obj;
            }
        }
        if (soapObject.hasProperty("name"))
        {
            Object obj = soapObject.getProperty("name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                name = j.toString();
            }else if (obj!= null && obj instanceof String){
                name = (String) obj;
            }
        }
        if (soapObject.hasProperty("_class"))
        {
            Object obj = soapObject.getProperty("_class");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                _classField = j.toString();
            }else if (obj!= null && obj instanceof String){
                _classField = (String) obj;
            }
        }
        if (soapObject.hasProperty("notice"))
        {
            Object obj = soapObject.getProperty("notice");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                notice = j.toString();
            }else if (obj!= null && obj instanceof String){
                notice = (String) obj;
            }
        }
        if (soapObject.hasProperty("send_to__c"))
        {
            Object obj = soapObject.getProperty("send_to__c");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                send_to__c = j.toString();
            }else if (obj!= null && obj instanceof String){
                send_to__c = (String) obj;
            }
        }
        if (soapObject.hasProperty("signature__c"))
        {
            Object obj = soapObject.getProperty("signature__c");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                signature__c = j.toString();
            }else if (obj!= null && obj instanceof String){
                signature__c = (String) obj;
            }
        }
        if (soapObject.hasProperty("subject__c"))
        {
            Object obj = soapObject.getProperty("subject__c");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                subject__c = j.toString();
            }else if (obj!= null && obj instanceof String){
                subject__c = (String) obj;
            }
        }
        if (soapObject.hasProperty("posteddate"))
        {
            Object obj = soapObject.getProperty("posteddate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                posteddate = j.toString();
            }else if (obj!= null && obj instanceof String){
                posteddate = (String) obj;
            }
        }
        if (soapObject.hasProperty("noticecount"))
        {
            Object obj = soapObject.getProperty("noticecount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                noticecount = j.toString();
            }else if (obj!= null && obj instanceof String){
                noticecount = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return noticeid;
            case 1:
                return name;
            case 2:
                return _classField;
            case 3:
                return notice;
            case 4:
                return send_to__c;
            case 5:
                return signature__c;
            case 6:
                return subject__c;
            case 7:
                return posteddate;
            case 8:
                return noticecount;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 9;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "noticeid";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "name";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "_class";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "notice";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "send_to__c";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "signature__c";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "subject__c";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "posteddate";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "noticecount";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
